config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  get 'profiles/show'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  before_action :owned_profile, only: [:edit, :update]

  def show
    @user = User.find_by(user_name: params[:user_name])
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end

  def edit
    @user = User.find_by(user_name: params[:user_name])
  end

  def update
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      redirect_to profile_path(@user.user_name)
    else
      render :edit
    end
    # render plain: params[:user].inspect
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    @user = User.find_by(user_name: params[:user_name])
    unless current_user == @user
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "That profile doesn't belong to you!" }
        format.json { head :no_content }
      # flash[:alert] = "That profile doesn't belong to you!"
      # redirect_to root_path
      end
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
   end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: update_profile_path, local: true do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your Profile Picture</h4>
                <div class="img-circle">
                </div>
                <%= f.file_field :avatar %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="showprofilecontainer">
  <div class="posts-wrapper">
    <div class="row profile-header">
      <div class="col-md-6">
        <div id="imgborder">
          <div class="img-circle">
            <%= image_tag @user.avatar_url.to_s, id: 'avatar-image' %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="user-name-and-follow">
          <h3 class="profile-user-name">
            <%= @user.user_name %>
          </h3>
          <span>
            <% if @user == current_user %>
              <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button' %>
            <% end %>
          </span>
        </div>
        <p class="profile-bio">
          <p>Bio: <%= @user.bio %></p>
        </p>
        <div class="user-statistics">
          <p>
           Posts: <%= @user.posts.count %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% @posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
</div>