config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  get 'profiles/show'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

end

app/models/notification.rb
class Notification < ApplicationRecord
  validates :user_id, :notified_by_id, :post_id, :identifier,
  :notice_type, presence:true
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end

  # def index
  #   @notifications = current_user.notifications
  # end
  
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
  <%= link_to "#{notification.notified_by.user_name} has #{notification.notice_type}ed on your post", link_through_path(notification) %>
</li>

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">
    <button class="btn btn-default dropdown-toggle" type='button', id='dropdownMenu1', data-toggle='dropdown', aria-haspopup='true', aria-expanded='true'>
        <%= current_user.notifications.where(read:nil).count %>
        <span class="glyphicon glyphicon-flag"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby='dropdownMenu1'>
        <li class="dropdown-header text-center">Notifications</li>  
            <%= render current_user.notifications.where(read:nil).last(5).reverse %>
        <li class="divider" role="separator">
            <li class="text-center">
                <%= link_to "New Post", new_post_path %>
            </li>
        </li>
    </ul>
    
</div>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="notification-index-list">
        <%= render @notifications %>
      </ul>
    </div>
  </div>
</div>
<% @notifications.each do |notification| %>
  <%= render 'notification', notification: notification %>
<% end %>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>