config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  get 'profiles/show'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to image_tag("petgramlogo.png", :size => "165x30"), root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= render 'notifications/notification_dropdown' %>
          </li>
          <li>
            <%= link_to current_user.user_name, profile_path(current_user.user_name) %>
          </li>  
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'logo.png' %>
    <title>Petgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'layouts/navbar' %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    
  </head>

  <body>
    <%= yield %>
  </body>
</html>